// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformHR.Models;

namespace PlatformHR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220317122222_DatabaseInitializer")]
    partial class DatabaseInitializer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlatformHR.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = 641234567,
                            DateOfBirth = new DateTime(1988, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bl@gmail.com",
                            FullName = "Branko Lazic"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = 641234567,
                            DateOfBirth = new DateTime(1986, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lm@gmail.com",
                            FullName = "Luka Mitrovic"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = 641234567,
                            DateOfBirth = new DateTime(1982, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ms@gmail.com",
                            FullName = "Marko Simonovic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
